import { CountryName } from './country-name.interface';
import { Currencies } from './currencies.interface';
import { Idd } from './idd.interface';
import { CountryTranslations } from './translations.interface';
import { CountryDemonyms } from './demonyms.interface';
import { CountryCapitalInfo } from './capital-info.interface';
import { CountryPostalCode } from './postal-code.interface';
import { Flag } from './flag.interface';
import { CountryCoatOfArms } from './coat-of-arms.interface';
import { CountryMaps } from './maps.interface';

export interface Country {
  name: CountryName;
  tld?: string[];
  cca2: string;
  ccn3?: string;
  cca3: string;
  cioc?: string;
  independent?: boolean;
  status: string;
  unMember: boolean;
  currencies?: Currencies;
  idd: Idd;
  capital?: string[];
  altSpellings: string[];
  region: string;
  subregion?: string;
  languages?: { [key: string]: string };
  translations?: CountryTranslations;
  latlng: number[];
  landlocked: boolean;
  borders?: string[];
  area: number;
  demonyms?: CountryDemonyms;
  flag: string;
  maps: CountryMaps;
  population: number;
  gini?: { [key: string]: number };
  fifa?: string;
  car: { signs?: string[]; side: string };
  timezones: string[];
  continents: string[];
  flags: Flag;
  coatOfArms?: CountryCoatOfArms;
  startOfWeek: string;
  capitalInfo: CountryCapitalInfo;
  postalCode?: CountryPostalCode;
}